VISIBILITY_PROJECT = "project"
VISIBILITY_ORGANIZATION = "organization"
VISIBILITY_SCOPES = (VISIBILITY_PROJECT, VISIBILITY_ORGANIZATION)

EFFECT_ALLOW = "allow"
EFFECT_DENY = "deny"
PERMISSION_EFFECTS = (EFFECT_ALLOW, EFFECT_DENY)

SESSION_TYPE_ACCESS = "access"
SESSION_TYPE_REFRESH = "refresh"
SESSION_TYPES = (SESSION_TYPE_ACCESS, SESSION_TYPE_REFRESH)
